version: "3"

services:
  yt-dlp-web:
    image: sooros5132/yt-dlp-web
    container_name: yt-dlp-web
    user: 1000:1000
    # environment:
    #   If you need to protect the site, set AUTH_SECRET, CREDENTIAL_USERNAME, CREDENTIAL_PASSWORD.
    #   AUTH_SECRET: "ruDKYjFEdS7Pc9krz+6VcYzpfJXQzWxkEBpwLkPbhIMx+UsYQF7oCAaMiSU="
    #   CREDENTIAL_USERNAME: "nadnaws"
    #   CREDENTIAL_PASSWORD: "nadnaws"
    volumes:
      - ~/Desktop/downloads:/downloads
      - ~/Desktop/cache:/cache
    ports:
      - 3000:3000
    restart: unless-stopped
